### ISSUE TITLE
cp_mgmt_access_rule action "Apply Layer" != "Inner Layer"

### ISSUE THREAD

**Issue by alex-barth** [CheckPointSW/CheckPointAnsibleMgmtCollection#37] opened 2021-03-15 16:01 UTC
Hi,

I'm using the module cp_mgmt_access_rule from the collection 2.0.0. 

I just had the issue, that rules with the action `Apply Layer` always report as changed.
After some searching I found that the API returns the action name as `Inner Layer` instead of `Apply Layer`. Which is also wrong in the [management API reference](https://sc1.checkpoint.com/documents/latest/APIs/#cli/show-access-rule~v1.7%20)

I tried using `Inner Layer` as an action in the module instead, but the API rejects it.

I hope that you can help me.

Thanks,
Alex

**Comment by chkp-orso** [comment] 2021-03-16 17:27
Hi Alex,

Can you please share your:
1. playbook
2. error message
3. the rule itself (you can use the module cp_mgmt_access_rule_facts in order to get the rule)

Thanks,
Or

**Comment by alex-barth** [comment] 2021-03-17 07:54
Hi Or,

sure, thanks for investigating.

**1. playbook:**
```
---
- name: recreate issue 37
  hosts: all
  gather_facts: no
  connection: httpapi
  vars:
    ansible_python_interpreter: auto
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: check_point.mgmt.checkpoint

  tasks:
    - name: create layer
      cp_mgmt_access_layer:
        name: "layer123"
        auto_publish_session: true
    
    - name: create "normal" rule
      cp_mgmt_access_rule:
        layer: "Network"
        position: "1"
        name: "normal rule"
        source: "Any"
        destination: "Any"
        service: "ssh"
        action: "Accept"
        state: present
        auto_publish_session: true

    - name: 'create "normal" rule again - expected: no changes, actual: no changes'
      cp_mgmt_access_rule:
        layer: "Network"
        position: "1"
        name: "normal rule"
        source: "Any"
        destination: "Any"
        service: "ssh"
        action: "Accept"
        state: present
        auto_publish_session: true

    - name: create "Apply Layer" rule
      cp_mgmt_access_rule:
        layer: "Network"
        position: "2"
        name: "layer rule"
        source: "Any"
        destination: "Any"
        service: "dns"
        action: "Apply Layer"
        inline_layer: "layer123"
        state: present
        auto_publish_session: true

    - name: show "Apply Layer" rule facts
      cp_mgmt_access_rule_facts:
        layer: "Network"
        name: "layer rule"
      register: __result

    # 'Inner Layer' instead of 'Apply Layer' is printed
    - name: print action name
      debug:
        msg: "action name: {{ __result['ansible_facts']['access-rule']['action']['name'] }}"

    - name: print rule
      debug:
        var: __result['ansible_facts']['access-rule']

    - name: 'create "Apply Layer" rule again - expected: no changes, actual: changed'
      cp_mgmt_access_rule:
        layer: "Network"
        position: "2"
        name: "layer rule"
        source: "Any"
        destination: "Any"
        service: "dns"
        action: "Apply Layer"
        inline_layer: "layer123"
        state: present
        auto_publish_session: true

```

**output**
```
PLAY [recreate issue 37] **********************************************************************************************
TASK [create layer] ***************************************************************************************************
changed: [T-ORC-FW-MGT-ABARTH]

TASK [create "normal" rule] *******************************************************************************************
changed: [T-ORC-FW-MGT-ABARTH]

TASK [create "normal" rule again - expected: no changes, actual: no changes] *****************************************
ok: [T-ORC-FW-MGT-ABARTH]

TASK [create "Apply Layer" rule] **************************************************************************************
changed: [T-ORC-FW-MGT-ABARTH]

TASK [show "Apply Layer" rule facts] **********************************************************************************
ok: [T-ORC-FW-MGT-ABARTH]

TASK [print action name] **********************************************************************************************
ok: [T-ORC-FW-MGT-ABARTH] => {
    "msg": "action name: Inner Layer"
}

TASK [print rule] *****************************************************************************************************
ok: [T-ORC-FW-MGT-ABARTH] => {
    "__result['ansible_facts']['access-rule']": {
        "action": {
            "domain": {
                "domain-type": "data domain",
                "name": "Check Point Data",
                "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"    
            },
            "name": "Inner Layer",
            "type": "Global",
            "uid": "ea28da66-c5ed-11e2-bc66-aa5c6188709b"        
        },
        "action-settings": {},
        "comments": "",
        "content": [
            {
                "domain": {
                    "domain-type": "data domain",
                    "name": "Check Point Data",
                    "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"
                },
                "name": "Any",
                "type": "CpmiAnyObject",
                "uid": "97aeb369-9aea-11d5-bd16-0090272ccb30"    
            }
        ],
        "content-direction": "any",
        "content-negate": false,
        "custom-fields": {
            "field-1": "",
            "field-2": "",
            "field-3": ""
        },
        "destination": [
            {
                "domain": {
                    "domain-type": "data domain",
                    "name": "Check Point Data",
                    "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"
                },
                "name": "Any",
                "type": "CpmiAnyObject",
                "uid": "97aeb369-9aea-11d5-bd16-0090272ccb30"
            }
        ],
        "destination-negate": false,
        "domain": {
            "domain-type": "domain",
            "name": "SMC User",
            "uid": "41e821a0-3720-11e3-aa6e-0800200c9fde"
        },
        "enabled": true,
        "inline-layer": {
            "domain": {
                "domain-type": "domain",
                "name": "SMC User",
                "uid": "41e821a0-3720-11e3-aa6e-0800200c9fde"
            },
            "name": "layer123",
            "type": "access-layer",
            "uid": "ec76153e-c3d4-4960-bf15-dc3fc35274fe"
        },
        "install-on": [
            {
                "domain": {
                    "domain-type": "data domain",
                    "name": "Check Point Data",
                    "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"
                },
                "name": "Policy Targets",
                "type": "Global",
                "uid": "6c488338-8eec-4103-ad21-cd461ac2c476"
            }
        ],
        "layer": "63b7fe60-76d2-4287-bca5-21af87337b0a",
        "meta-info": {
            "creation-time": {
                "iso-8601": "2021-03-17T08:39+0100",
                "posix": 1615966753076
            },
            "creator": "admin",
            "last-modifier": "admin",
            "last-modify-time": {
                "iso-8601": "2021-03-17T08:39+0100",
                "posix": 1615966753256
            },
            "lock": "unlocked",
            "validation-state": "ok"
        },
        "name": "layer rule",
        "service": [
            {
                "domain": {
                    "domain-type": "data domain",
                    "name": "Check Point Data",
                    "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"
                },
                "name": "dns",
                "type": "service-group",
                "uid": "97aeb46b-9aea-11d5-bd16-0090272ccb30"
            }
        ],
        "service-negate": false,
        "source": [
            {
                "domain": {
                    "domain-type": "data domain",
                    "name": "Check Point Data",
                    "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"
                },
                "name": "Any",
                "type": "CpmiAnyObject",
                "uid": "97aeb369-9aea-11d5-bd16-0090272ccb30"
            }
        ],
        "source-negate": false,
        "time": [
            {
                "domain": {
                    "domain-type": "data domain",
                    "name": "Check Point Data",
                    "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"
                },
                "name": "Any",
                "type": "CpmiAnyObject",
                "uid": "97aeb369-9aea-11d5-bd16-0090272ccb30"
            }
        ],
        "track": {
            "accounting": false,
            "alert": "none",
            "enable-firewall-session": false,
            "per-connection": false,
            "per-session": false,
            "type": {
                "domain": {
                    "domain-type": "data domain",
                    "name": "Check Point Data",
                    "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"
                },
                "name": "None",
                "type": "Track",
                "uid": "29e53e3d-23bf-48fe-b6b1-d59bd88036f9"
            }
        },
        "type": "access-rule",
        "uid": "4e67e464-a00b-412b-a6a9-a6eee1d7a21d",
        "vpn": [
            {
                "domain": {
                    "domain-type": "data domain",
                    "name": "Check Point Data",
                    "uid": "a0bbbc99-adef-4ef8-bb6d-defdefdefdef"
                },
                "name": "Any",
                "type": "CpmiAnyObject",
                "uid": "97aeb369-9aea-11d5-bd16-0090272ccb30"
            }
        ]
    }
}

TASK [create "Apply Layer" rule again - expected: no changes, actual: changed] ***************************************
changed: [T-ORC-FW-MGT-ABARTH]

PLAY RECAP ************************************************************************************************************
T-ORC-FW-MGT-ABARTH        : ok=8    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
**2. error message**
There is no error message, its more like unexpected behaviour. It should not report the rule as changed if nothing has changed.

**3. the rule itself**
_included in the playbook output above_

Thanks,
Alex

**Comment by alex-barth** [comment] 2021-04-12 11:23
@chkp-orso

Any updates?

Thanks,
Alex

**Comment by chkp-orso** [comment] 2021-05-30 11:20
Hi @alex-barth 
Thanks! found the problem.
The problem is in the backend side of Check Point so it can't be fixed in a "collection" version, but it will be fixed in Check Point backend code.

Thanks for find this!

**Closed by chkp-orso** 2021-05-30 11:20 UTC
